name = "DecqedMesher"
uuid = "80ed94e9-0240-4013-a43c-6bae10997507"
authors = ["Richard D. Li, Dzung N. Pham, Hakan E. Türeci"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
